### ISSUE TITLE
milvus向量库

### ISSUE THREAD

**Issue by Tomriy** [spring-projects-experimental/spring-ai#19]
为什么不用milvus作为向量数据库呢？

**Comment by tzolov** [comment]
Hi @Tomriy,  can we use common English please ;)
I'm guessing you are asking for Milvus Vector DB support?

**Comment by tzolov** [comment]
@Tomriy, by coincidence, over the weekend I've put together a Milvus store prototype:  https://github.com/spring-projects-experimental/spring-ai/pull/20
Feel free to review/test it. 
Suggestions are welcome.
