### ISSUE TITLE
AI client library

### ISSUE THREAD

**Issue by ideaplugins** [spring-projects-experimental/spring-ai#2]
Apologies for creating an issue to only ask a question, but I don't see the discussions enabled for this repository.

Why don't you use [Azure client library](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/openai/azure-ai-openai) instead of theokanning client? Did you consider it?

It provides sync and async clients. And it's very easy to switch from Azure API to Open AI API

**Comment by markpollack** [comment]
No problem, I welcome questions here, not sure what is a better medium for that.  A discord server?  I needed two implementations to make sure the abstraction was correct, so this was one way to do it.  Also, I believe there are other features added into the Azure client that I didn't see in the Theo Kanning one, but I didn't dive into too much detail.  It can be something to consider, but having two implementations of a 'common' API was crucial.  I'll take some time to do a more careful comparison between the two offerings and think about this question more.  Thanks again.

**Comment by ideaplugins** [comment]
I see, you use Theo Kanning's client for the openAi module, and the Azure client only in the azure module :+1:
