### ISSUE TITLE
We'd love to add Neo4j as a vector store to the project

### ISSUE THREAD

**Issue by jexp** [spring-projects-experimental/spring-ai#26]
Neo4j added vector support in August 2023 based on HNSW, we'd like to add support for that to spring-ai

Just wanted to open an issue first before sending in a PR, to see if there are any thoughts.

**Comment by tzolov** [comment]
Hey @jexp , thanks for raising this issue. 
Looking forward for your PR!

**Comment by markpollack** [comment]
PR was merged as a6fba7a3b6306b64c48cc881ecdc89096d3dd98f

**Comment by michael-simons** [comment]
Great news!!
