### ISSUE TITLE
Support PostgresML as an `EmbeddingClient`

### ISSUE THREAD

**Issue by making** [spring-projects-experimental/spring-ai#33]
It would be nice to support PostgresML embeddings (https://postgresml.org/docs/guides/transformers/embeddings) as an `EmbeddingClient` that doesn't require OpenAI/Azure OpenAI account

**Comment by markpollack** [comment]
Please follow the current packaging style and provide an integration test.

**Comment by markpollack** [comment]
I love your dog!
