### ISSUE TITLE
Add Neo4j as a Vector Store

### ISSUE THREAD

**Issue by radhakrishna67** [spring-projects-experimental/spring-ai#36]
Current Version of the Spring AI allows InMemoryVectorStore but  Neo4jVectorStore is expected along with it.

Expected Behavior

Neo4j should be able to use as VectorStore

Current Behavior

InMemoryVectorStore is supported.

Context

I am working on content writer suggestions use-case with azure openai embedding stored in Neo4j. So i request the team to implement Neo4j as Vector Store

**Comment by meistermeier** [comment]
We contributed a Neo4j module a few days ago and it got merged ~10 hours ago.
https://github.com/spring-projects-experimental/spring-ai/issues/26

**Comment by tzolov** [comment]
@radhakrishna67
in addition to the in-memory (and persistent) stores you you can already use one of the following vector store integrations as well:

* [PGVector](https://github.com/spring-projects-experimental/spring-ai/tree/main/vector-stores/spring-ai-pgvector-store)
* [Milvus](https://github.com/spring-projects-experimental/spring-ai/tree/main/vector-stores/spring-ai-milvus-store)
* [Neo4j](https://github.com/spring-projects-experimental/spring-ai/tree/main/vector-stores/spring-ai-neo4j-store)

The `pinecone` integration is in progres.

**Comment by radhakrishna67** [comment]
@meistermeier, thank you so much for your contribution with Neo4j.

@tzolov, Spring AI is now supporting great set of Vector stores. Are there any chances of considering Chroma Vector store?

**Comment by tzolov** [comment]
Duplication. 
Resolved with https://github.com/spring-projects-experimental/spring-ai/issues/26
